# These are the "base" classes and attributes every game, no matter what will
#   inherit from.
# DO NOT CHANGE THESE VALUES UNLESS YOU KNOW WHAT YOU ARE DOING
# - These values effect ALL the games, so please be cautious

AI:
  description: The AI competitors will add logic to this AI so its functions return valid and smart values.

Game:
  # these are special game server values
  numberOfPlayers: 2
  #maxInvalidsPerPlayer: 10
  attributes:
    gameObjects:
      type:
        name: dictionary
        keyType: string
        valueType: const GameObject!
      description: A mapping of every game object's ID to the actual game object. Primarily used by the server and client to easily refer to the game objects via ID.
      serverPredefined: true
    players:
      type: Player[]
      description: List of all the players in the game.
      serverPredefined: true
    session:
      type: const string
      description: A unique identifier for the game instance that is being played.
      serverPredefined: true

GameObject:
  description: An object in the game. The most basic class that all game classes should inherit from automatically.
  attributes:
    id:
      type: const string
      description: A unique id for each instance of a GameObject or a sub class. Used for client and server communication. Should never change value after being set.
      serverPredefined: true
    gameObjectName:
      type: const string
      description: String representing the top level Class that this game object is an instance of. Used for reflection to create new instances on clients, but exposed for convenience should AIs want this data.
      serverPredefined: true
    logs:
      type: string[]
      description: Any strings logged will be stored here. Intended for debugging.
      serverPredefined: true
  functions:
    log:
      description: Adds a message to this GameObject's logs. Intended for your own debugging purposes, as strings stored here are saved in the gamelog.
      serverPredefined: true
      altersState: true
      arguments:
      - name: message
        type: string
        description: A string to add to this GameObject's log. Intended for debugging.

Player:
  description: A player in this game. Every AI controls one player.
  attributes:
    name:
      type: const string
      description: The name of the player.
      default: Anonymous
    clientType:
      type: const string
      description: What type of client this is, e.g. 'Python', 'JavaScript', or some other language. For potential data mining purposes.
    won:
      type: boolean
      description: If the player won the game or not.
      default: false
    lost:
      type: boolean
      description: If the player lost the game or not.
      default: false
    reasonWon:
      type: string
      description: The reason why the player won the game.
    reasonLost:
      type: string
      description: The reason why the player lost the game.
    timeRemaining:
      type: float
      description: The amount of time (in ns) remaining for this AI to send commands.
